### ISSUE TITLE
Support for projects

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#14]
We should support projects in our domain model in order to allow users to associate them with their own skill profile. This is another kind of "experience" in addition to the skills related to a user.

Basic domain and API modeling:

* Projects should be another node entity type (just like skills).
* A project has the following properties:
  * Name (mandatory, unique, single text)
  * Customer (optional, single text)
  * Industry sector (optional, single text)
  * Description (optional, single text)
  * Creation date (mandatory, date+time, set by application)
  * Last modified date (mandatory, date+time, set by application)
* There should be a dedicated REST API to query and modify projects, e.g. with path `/projects`, similar to the skills API.
* Every authenticated user is authorized to query, create and modify projects at the moment.
* Only users with the `ADMIN` role are allowed to delete projects.

Relationship between users and projects:

* Projects can be related to users with the following properties on the relationship:
  * Role (optional, single text)
  * Tasks (optional, single text)
  * Start date (mandatory, date)
  * End date (optional, date)
  * Creation date (mandatory, date+time, set by application)
  * Last modified date (mandatory, date+time, set by application)
* The user-projects relationship is undirected many-to-many, i.e. a user can be related to multiple projects and a project can be associated with multiple users.
* There should be a REST API to query and modify user-projects relationships, e.g. with path `/users/{userId}/projects`, similar to the relationship between users and skills.
* Querying the user-projects for a specific user is only allowed to the owning user and those users who have been granted the permission scope `READ_USER_SKILLS` by the owning user. Similar to user-skills relationship.
* Creation, modification and deletion of user-projects relationships is only allowed to the owning user.

**Comment by LebedkoDmitry** [comment]
PR #22

**Comment by LebedkoDmitry** [comment]
Implemented in #22
