### ISSUE TITLE
Additional user profile properties

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#15]
The user should be able to provide additional, personal information in her/his user profile. This includes:

* Academic degree (optional, e.g. "Diplom-Wirtschaftsinformatiker")
* Position profile (optional, e.g. "Software Architect")
* Summary (optional, single text)
* Industry sectors (optional, list of texts, e.g. ["Automotive", "Telecommunication"])
* Specializations (optional, list of texts, e.g. ["IT Consulting", "Software Integration"])
* Certificates (optional, list of texts, e.g. ["Java Certified Programmer"])
* Languages (optional, list of texts, e.g. ["Deutsch"])

Extension of existing data model and API:

* The `User` node entity must be extended to store these additional properties. Lists of simple data types should be possible in Neo4j.
* The REST API `/users` must be extended to allow these additional properties to be received in request bodies and returned in responses.
* The REST API responses providing users as an embedded data structure or as simple references (e.g. `/skills/{skillId}/users`) should still use a simpler user data structure which does not contain these additional properties.
* Queries to the users REST API (e.g. `GET /users`  or `GET /users/{userId}`) should only return the additional properties for those users who have granted permission of scope `READ_USER_SKILLS` to the currently authenticated user and for the authenticated user herself/himself.

**Comment by LebedkoDmitry** [comment]
Implemented in #20
