### ISSUE TITLE
Update of user skill assignment fails due to security expression

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#23]
Description:

Saving updated values of a relationship between user and skill (e.g. changed priority) fails with the following error message:

`Failed to evaluate expression '#userSkill.user.userName.equals(authentication.userAuthentication.Principal.userName) || hasRole('ADMIN')'`

Expected behavior:

The user must be able to update the levels of skills in her/his skill profile.

Steps to reproduce:

1. Log in with a user to MySkills web app.
2. Go to "My skill profile" page.
3. Add a skill to the skill profile.
4. Edit the previously added skill assignment (click pencil icon).
5. Change some values and save.

**Comment by LebedkoDmitry** [comment]
Fixed in #26 

There has to be an additional discussion about "proper" place where to put security annotations - service or controller layer.
