### ISSUE TITLE
Provide outbound and inbound user permissions

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#24]
Currently, the MySkills Server only provides a REST API to query/update user permissions which the user has granted to other users (outbound permissions): `/users/{userId}/permissions`

For some future features we also need the query user permissions from the opposite perspective: Which user permissions have I been granted by other users (inbound permissions)? This is required for managers to obtain a list of users who have given them the permission to view their skill profiles.

Therefore, the API endpoints for outbound permissions should be refactored to use the path `/users/{userId}/outbound-permissions`.

A new API endpoint should be created to query the inbound permissions of a given user via `GET` request to `/users/{userId}/inbound-permissions`. The response should be a list of user permissions which other users have granted to the user denoted by `userId`.

**Comment by LebedkoDmitry** [comment]
PR #27 and https://github.com/KnowledgeAssets/myskills-webapp/pull/34

**Comment by LebedkoDmitry** [comment]
Implemented in #27 and https://github.com/KnowledgeAssets/myskills-webapp/pull/34
