### ISSUE TITLE
Neo4j Database Migration Using Liquigraph

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#51]
I have thought about our current approach of Neo4j database initialization and migration. We use the `IndexManager` to do migration manually because Neo4j OGM auto-indexing is limited (e.g. does not drop obsolete indexes) and therefore does not feel like a suitable solution for production.

Nevertheless, our current approach requires a lot of boilerplate code and still does not support incremental updates of the database. Therefore, I thought about introducing another framework which makes Neo4j database migration easier: https://www.liquigraph.org/latest/index.html

It works with change sets defined in XML format and takes care of incremental updates. There is also a Spring Boot integration, so we basically only need to provide the change log and get automatic database migration at application startup without writing any Java code.

@svetivanova @LebedkoDmitry What do you think? Should we give it a try?

**Comment by LebedkoDmitry** [comment]
I think we should give it a try. From my perspective there are following steps to be taken to have Liquigraph integrated:

1. Plug in the necessary libraries.
2. Expose configured `DataSource`.
3. Move `${project}/src/main/resources/migration/generated_indexes.cql` into `${project}/src/main/resources/db/liquigraph/changelog.xml` or one of its sub changelogs.
4. Check the indexes are automatically altered by Liquigraph.

This approach will eliminate the whole `io.knowledgeassets.myskills.server.neo4j` package and enable us to apply any necessary changes with Cypher queries, what is really great from my point of view.

**Comment by LebedkoDmitry** [comment]
Implemented in #52
