### ISSUE TITLE
Anonymous user profiles for specific skill requirements

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#8]
The MySkills Server should provide an API which allows users to find anonymous user profiles matching specific skill requirements. For example: Search for users who have Angular with a minimum current level of 3 and Spring Boot with a minimum current level of 2 in their profile.

Search for user profiles:

* There is a new API endpoint to perform searches for user profiles matching given skill requirements. For example: `GET /search/users`
* The API allows searching user profiles containing the given skills with the given minimum current levels. No other criteria at the moment.
* The API supports an arbitrary number of "skill + minimum current level" parameters. Parameters should be passed as URL query parameters if possible, so that we can perform a `GET` request.
* If multiple filtering parameters are given in the request then only those user profiles are returned which satisfy ALL of those criteria.
* The API can be accessed by anyone who is authenticated.
* The API does not filter user profiles by any user permission.

Response with anonymous user profiles:

* The API returns matching user profiles WITHOUT any data revealing the real user identity.
* Each matching user profile is returned with the following properties:
  * List of the skills given as criteria in the API request. Each skill contains the skill name and the current level of the user.
  * Anonymous reference ID. This is a UUID which can be used to download the anonymous user profile as a document later on. It CANNOT be the user ID for security reasons because this would allow querying the `/users/{userId}` API endpoint which reveals the real user identity.

In the future, each user entity node must be created with an additional "anonymous reference ID" property to allow referring to the user without revealing her/his original user ID. This reference ID MUST NOT be included in responses of the user API `/users` and `/users/{userId}` to prevent discovery.

**Comment by LebedkoDmitry** [comment]
Implemented in #28
