### ISSUE TITLE
Download Word document of anonymous user profiles

### ISSUE THREAD

**Issue by georgwittberger** [KnowledgeAssets/myskills-server#9]
Depends on #8 

The MySkills Server should provide an API which allows downloading a Word document with the anonymous skill profile for a given user.

Anonymous user reference:

* There is a new API endpoint allowing downloads of anonymous user skill profiles in Word format. For example: `GET /download/users/{refId}`
* The user to download the skill profile for must be referenced by an anonymous reference ID. We CANNOT use the user ID to request the download because revealing it allows querying the real user identity via `/users/{userId}`.
* The API is accessible for every authenticated user (valid access token), no special user permission required.

Document content:

* The downloaded document MUST NOT contain any data revealing the real user identity (e.g. user ID, user names, e-mail).
* The downloaded document contains the anonymous, general information from the user profile, i.e. academic degree, specializations, languages, etc. These information are printed in the section "General". Each information is printed as a new paragraph. Lists of values (e.g. languages) should be printed with bullet points.
* The downloaded document contains ALL skills related to the user including the current levels. The skill list is sorted by current level in descending order (highest levels first). It is printed in the section "Skills" of the document. For each skill the name and current level should be printed (level value as a number, corresponding amount of star icons if possible).

Word document download:

* The API responds with the binary Word document data and includes the appropriate `Content-Type` header value.
* The response includes the HTTP header `Content-Disposition: attachment; filename=user-profile.docx`.
* We must be careful with the used document generator library! Since our project is under MIT license we must pick some compatible library. Beware of frameworks under GPL or other copyleft licenses! Maybe [Apache POI](https://poi.apache.org/) is an option.

**Comment by LebedkoDmitry** [comment]
It seems that the libraries distributed under LGPL can be used without any issues as soon as there is no need to change their sources.
http://answers.google.com/answers/threadview/id/439136.html
https://stackoverflow.com/questions/2015805/how-can-i-legally-use-lgpl-javascript-in-a-commercial-web-site
Flying Saucer is distributed under LGPL 2.1 or later. 
OpenPDF is distributed under LGPL and MPL. Thus OpenPDF can either be used as soon as there is no need to copy / change its source code.
https://github.com/LibrePDF/OpenPDF
There is an alternative Apache PDFBox
https://github.com/apache/pdfbox
It is distributed under Apache License 2.0 so there are much less questions and risks.

**Comment by LebedkoDmitry** [comment]
There is an article by David Turner, GPL compliance engineer at the FSF:
https://www.gnu.org/licenses/lgpl-java.en.html
The most important extract from the article is:

> If you distribute a Java application that imports LGPL libraries, it's easy to comply with the LGPL. Your application's license needs to allow users to modify the library, and reverse engineer your code to debug these modifications. This doesn't mean you need to provide source code or any details about the internals of your application. Of course, some changes the users may make to the library may break the interface, rendering the library unable to work with your application. You don't need to worry about that—people who modify the library are responsible for making it work.

> When you distribute the library with your application (or on its own), you need to include source code for the library. But if your application instead requires users to obtain the library on their own, you don't need to provide source code for the library.

**Comment by LebedkoDmitry** [comment]
For example [org.quartz-scheduler.quartz 2.3.0](https://mvnrepository.com/artifact/org.quartz-scheduler/quartz/2.3.0) distributed under Apache 2.0 uses c3p0 0.9.5.2 distributed under LGPL 2.1.

![image](https://user-images.githubusercontent.com/2815502/51547654-05d7bc00-1e67-11e9-96da-e7e16f682c19.png)

**Comment by georgwittberger** [comment]
@LebedkoDmitry Very good research! I talked to a colleague at MMS about licensing as well. She wanted to investigate which licenses are suitable but did not manage to do so up to now.

I proposed FlyingSaucer because we used that in another project in former times and it was quite nice to work with. You can basically write a HTML document, style it with CSS and then burn everything into a PDF. It's really easy to generate nice-looking documents.

I have never used Apache PDFBox before. Maybe it would be worth investigating how it feels to generate a PDF document from scratch with this library. From a license point of view it would be the easiest pick for us. If it does not feel to complicated to generate some styled document with embedded fonts and images we should possibly go for PDFBox.

**Comment by LebedkoDmitry** [comment]
@georgwittberger , I have researched FlyingSaucer a little bit more thoroughly and found the following [here](http://flyingsaucerproject.github.io/flyingsaucer/r8/guide/users-guide-R8.html)
> For PDF output we rely on the iText library to generate PDF.

I went to the [iText GitHub repository](https://github.com/itext/itextpdf) and found that

> iText is licensed as AGPL software.

[AGPL](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) license is quite sophisticated and [tldrlegal](https://tldrlegal.com/) states the following

> It provides the same restrictions and freedoms as the GPLv3 but with an additional clause which makes it so that source code must be distributed along with web publication. Since web sites and services are never distributed in the traditional sense, the AGPL is the GPL of the web.

Thus I'd rather avoid using both iText and FlyingSaucer as it is not safe for us rely on the libraries under copy-left license.

I have found another option - [JasperReports](https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports/6.7.0). But according to maven dependency tree it also relies on iText.

![image](https://user-images.githubusercontent.com/2815502/51593239-f8b3df00-1ef1-11e9-9774-212b66c3482e.png)

So I would like to give PDFBox a try and see if it fits us well. As soon as I have some results on embedding of fonts and images with PDFBox I will post it here.

**Comment by LebedkoDmitry** [comment]
PDFBox is not able to build a PDF file from HTML / CSS templates. There is another option called [Apache FOP](https://xmlgraphics.apache.org/fop/) which leverages XML together with XSL-FO / XSLT to transform XML info PDF. But as far as I got XSL-FO have to be developed manually. It will increase the amount of time for development / maintenance.

There is [OpenPDF](https://github.com/LibrePDF/OpenPDF) project which is based on iText and is [integrated](https://mvnrepository.com/artifact/org.xhtmlrenderer/flying-saucer-pdf-openpdf) with FlyingSaucer. It is available under LGPL 3.0 and MPL 2.0.

As I wrote above LGPL is not an issue as far as we don't change a library or build our own library on top of it. To keep it simple MPL 2.0 is a light version of LGPL  (see Q12 [here](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)) and as far as we do not change or copy any MPLed source files the project complies MPL 2.0 (Q7 [here](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)).

So from my point of view the best option is to use FlyingSaucer with OpenPDF.

**Comment by LebedkoDmitry** [comment]
UPDATE:

> The new info from the project team: It would be necessary to export the anonymous user profiles as Word documents as well. Word is even more important for our sales colleagues because they need to edit some things before sending those files to customers.

Thus Word file containing anonymous user profile should be generated instead of PDF files.
[Apache POI](https://poi.apache.org/) lets to create / read / modify doc / docx files.

After the investigation it was decided to stick with Apache POI.

**Comment by LebedkoDmitry** [comment]
PR #29

**Comment by LebedkoDmitry** [comment]
Implemented in #29
